### PR TITLE
 Rebuild for ipopt3148  and increase timeout

### PR DESCRIPTION
**Pull request by traversaro**
Supersede https://github.com/conda-forge/pagmo-feedstock/pull/61 .

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by bluescarni** [comment]
Thanks a lot @traversaro !

**Comment by traversaro** [comment]
In emulated test of the cross-compiled ppc64 build there was an error:
~~~ 
12/90 Test #13: cec2014 ..........................***Failed    2.89 sec
Running 3 test cases...
unknown location(0): fatal error: in "cec2014_test": memory access violation at address: 0x4000468000: no mapping at fault address
$SRC_DIR/tests/cec2014.cpp(68): last checkpoint

*** 1 failure is detected in the test module "cec2014_test"
~~~

However, switching to native builds the problem disappeared.

**Comment by bluescarni** [comment]
Yep I noticed that, not sure what is going on. In the CI we have builds with memory checking instrumentation enabled and never experienced any issues with that test.

I had issues in the past with link-time optimisation on PPC64, and that's the reason LTO/IPO is disabled in the build script:

https://github.com/conda-forge/pagmo-feedstock/blob/main/recipe/build.sh#L26

Perhaps the ``if test "$target_platform" != "linux-ppc64le"`` test does not trigger in cross-compilation mode?

**Comment by traversaro** [comment]
>
> Perhaps the `if test "$target_platform" != "linux-ppc64le"` test does not trigger in cross-compilation mode?

In theory it should be triggered, but it is possible that something is going wrong.

**Pull request merged**
