### PR TITLE
Rebuild for nlopt 2.8

### PR DESCRIPTION
**Pull request by jschueller**
Closes #82

### CODE REVIEW

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Comment by jschueller** [comment]
hi @bluescarni this is good to go imho

**Comment by jschueller** [comment]
hi @bluescarni this is good to go imho

**Comment by bluescarni** [comment]
@jschueller cheers!

**Pull request merged**
